from django.core.management.base import BaseCommand
from cafe.models import Category, MenuItem, DeliveryPartner

class Command(BaseCommand):
    help = "Seeds Farzi Cafe menu items, categories, and delivery partners"

    def handle(self, *args, **kwargs):
        self.stdout.write("Seeding Farzi Cafe database...")

        c_sips, _ = Category.objects.get_or_create(
            slug="molecular-sips",
            defaults={"name": "Farzi Molecular Sips", "icon": "🍸", "description": "Smoked cocktails, vapor infusions, and molecular mocktails.", "display_order": 1}
        )
        c_tapas, _ = Category.objects.get_or_create(
            slug="avant-garde-tapas",
            defaults={"name": "Avant-Garde Tapas & Bao", "icon": "🍔", "description": "Whimsical fusion bites, charcoal baos, and artisanal sliders.", "display_order": 2}
        )
        c_mains, _ = Category.objects.get_or_create(
            slug="claypot-mains",
            defaults={"name": "Smoked Claypot & Mains", "icon": "🥘", "description": "Slow-braised gravies, tandoori delicacies, and contemporary pots.", "display_order": 3}
        )
        c_desserts, _ = Category.objects.get_or_create(
            slug="nitro-desserts",
            defaults={"name": "Liquid Nitrogen Desserts", "icon": "🍨", "description": "Sub-zero frozen delicacies and reimagined Indian sweets.", "display_order": 4}
        )
        c_combos, _ = Category.objects.get_or_create(
            slug="turbo-combos",
            defaults={"name": "Farzi Turbo Express Combos", "icon": "⚡", "description": "Curated gourmet boxes packaged for 15-minute guaranteed dispatch.", "display_order": 5}
        )

        items = [
            {
                "name": "Farzi Mist Molecular Cocktail",
                "slug": "farzi-mist-cocktail",
                "category": c_sips,
                "price": 349.00,
                "tagline": "Cold-Pressed Citrus & Molecular Smoke Mist",
                "description": "Signature Farzi potion made with blood orange reduction, yuzu fizz, and aromatic dry ice mist in a crystal goblet.",
                "ingredients": "Blood Orange Puree, Japanese Yuzu Soda, Activated Rosemary Smoke, Dry Ice Mist, Citrus Spheres",
                "is_veg": True,
                "is_signature": True,
                "prep_time_mins": 4,
                "calories": 180,
                "spice_level": 0,
                "model_type": "cocktail",
                "rating": 4.96,
                "reviews_count": 234,
                "featured": True,
            },
            {
                "name": "Smoked Bourbon Illusion",
                "slug": "smoked-bourbon-illusion",
                "category": c_sips,
                "price": 389.00,
                "tagline": "Oakwood Smoked Caramel & Saffron Infusion",
                "description": "Velvety non-alcoholic malt base infused with burnt orange peel, Madagascar vanilla, and wood smoke.",
                "ingredients": "Oakwood Smoked Caramel, Ginger Malt, Saffron Fog, Candied Blood Orange, Golden Glaze",
                "is_veg": True,
                "is_signature": True,
                "prep_time_mins": 5,
                "calories": 210,
                "spice_level": 0,
                "model_type": "cocktail",
                "rating": 4.92,
                "reviews_count": 167,
                "featured": False,
            },
            {
                "name": "Electric Blue Galaxy Spark",
                "slug": "electric-blue-galaxy-spark",
                "category": c_sips,
                "price": 329.00,
                "tagline": "Butterfly Pea Flower & Shimmering Luster",
                "description": "Cosmic color-shifting elixir with lychee pearls, citric acid spheres, and celestial edible pearlescent shimmer.",
                "ingredients": "Butterfly Pea Flower Tea, Fresh Lychee Caviar, Sparkling Tonic Water, Elderflower Syrup, Blue Shimmer Dust",
                "is_veg": True,
                "is_signature": False,
                "prep_time_mins": 4,
                "calories": 160,
                "spice_level": 0,
                "model_type": "cocktail",
                "rating": 4.88,
                "reviews_count": 98,
                "featured": False,
            },
            {
                "name": "Dal Chawal Arancini Pops",
                "slug": "dal-chawal-arancini-pops",
                "category": c_tapas,
                "price": 429.00,
                "tagline": "Lentil Risotto Spheres with Achar Mayo & Poppadum Roll",
                "description": "Iconic Farzi creation! Yellow lentil & basmati rice morphed into golden Italian arancini balls with tangy pickle aioli.",
                "ingredients": "Crispy Dal Risotto Crust, Burrata Melting Core, Tangy Mango Pickle Aioli, Mini Poppadum Roll, Micro Coriander",
                "is_veg": True,
                "is_signature": True,
                "prep_time_mins": 7,
                "calories": 380,
                "spice_level": 1,
                "model_type": "arancini",
                "rating": 4.97,
                "reviews_count": 412,
                "featured": True,
            },
            {
                "name": "Truffle Galouti Slider",
                "slug": "truffle-galouti-slider",
                "category": c_tapas,
                "price": 499.00,
                "tagline": "Melt-in-Mouth Kebab with Black Truffle Butter on Brioche",
                "description": "Lucknowi mutton galouti kebab with 160 spices, crowned with black truffle emulsion and caramelized onions in toasted brioche.",
                "ingredients": "Lucknowi Spiced Minced Galouti, Black Truffle Emulsion, Golden Butter Brioche, Pickled Shallot Rings, Mint Gel",
                "is_veg": False,
                "is_signature": True,
                "prep_time_mins": 8,
                "calories": 520,
                "spice_level": 2,
                "model_type": "burger",
                "rating": 4.98,
                "reviews_count": 560,
                "featured": True,
            },
            {
                "name": "Wild Mushroom & Charcoal Truffle Bao",
                "slug": "charcoal-truffle-bao",
                "category": c_tapas,
                "price": 449.00,
                "tagline": "Activated Charcoal Steamed Buns with Porcini Foam",
                "description": "Pillowy pitch-black steamed bao filled with wok-tossed forest mushrooms, porcini reduction, and crispy leek ribbons.",
                "ingredients": "Activated Charcoal Bao Bun, Glazed Shiitake & Porcini Mushrooms, Truffle Aerated Foam, Crispy Leeks, Togarashi Dust",
                "is_veg": True,
                "is_signature": False,
                "prep_time_mins": 6,
                "calories": 340,
                "spice_level": 1,
                "model_type": "bao",
                "rating": 4.89,
                "reviews_count": 143,
                "featured": False,
            },
            {
                "name": "Tempura Fried Dynamite Prawns",
                "slug": "tempura-dynamite-prawns",
                "category": c_tapas,
                "price": 579.00,
                "tagline": "Crisp Rock Prawns Drizzled with Tobiko Molecular Glaze",
                "description": "Jumbo tiger prawns fried to golden airy crunch, tossed in spicy sriracha honey emulsion and crowned with popping orange caviar.",
                "ingredients": "Crispy Tiger Prawns, Japanese Tempura Batter, Honey Sriracha Glaze, Orange Tobiko Caviar, Chive Batons",
                "is_veg": False,
                "is_signature": True,
                "prep_time_mins": 8,
                "calories": 460,
                "spice_level": 2,
                "model_type": "arancini",
                "rating": 4.94,
                "reviews_count": 320,
                "featured": False,
            },
            {
                "name": "Fiery Ghost Pepper Wings",
                "slug": "fiery-ghost-pepper-wings",
                "category": c_tapas,
                "price": 479.00,
                "tagline": "Bhut Jolokia Smoked Glaze with Cooling Mint Pearls",
                "description": "Double-dredged crisp chicken wings glazed with Assam ghost pepper sauce, tempered by molecular cooling mint yogurt caviar.",
                "ingredients": "Double Crispy Wings, Smoked Bhut Jolokia Glaze, Molecular Mint Yogurt Spheres, Toasted Sesame, Celery Ribbons",
                "is_veg": False,
                "is_signature": False,
                "prep_time_mins": 8,
                "calories": 560,
                "spice_level": 3,
                "model_type": "arancini",
                "rating": 4.85,
                "reviews_count": 210,
                "featured": False,
            },
            {
                "name": "C.T.M. - Chicken Tikka Masala in Clay Pot",
                "slug": "chicken-tikka-masala-claypot",
                "category": c_mains,
                "price": 549.00,
                "tagline": "Tandoor Charred Morsels in Smoked Makhani Gravy",
                "description": "Succulent chicken tikka smoked in earthen claypot with rich velvet cashew-tomato gravy, served with crisp naan wafers.",
                "ingredients": "Claypot Charred Chicken, Slow-Simmered Tomato Cashew Makhani, Fenugreek Cream, Crisp Naan Crostini, Rose Petal Dust",
                "is_veg": False,
                "is_signature": True,
                "prep_time_mins": 9,
                "calories": 680,
                "spice_level": 2,
                "model_type": "curry",
                "rating": 4.97,
                "reviews_count": 640,
                "featured": True,
            },
            {
                "name": "Deconstructed Paneer Makhani Sphere",
                "slug": "paneer-makhani-sphere",
                "category": c_mains,
                "price": 489.00,
                "tagline": "Cottage Cheese Pillow stuffed with Burrata in Makhani Pool",
                "description": "Silken paneer roulade injected with Italian burrata cream, resting in a glowing bath of velvet tomato reduction.",
                "ingredients": "Artisanal Malai Paneer, Fresh Burrata Heart, Smoked Makhani Reduction, Charred Cumin Butter, Micro Basil",
                "is_veg": True,
                "is_signature": False,
                "prep_time_mins": 8,
                "calories": 590,
                "spice_level": 1,
                "model_type": "curry",
                "rating": 4.91,
                "reviews_count": 285,
                "featured": False,
            },
            {
                "name": "Smoked Lamb Shank Rogan Josh Bowl",
                "slug": "smoked-lamb-shank-rogan-josh",
                "category": c_mains,
                "price": 689.00,
                "tagline": "Slow-Braised Kashmiri Spice Infusion with Saffron Rice",
                "description": "Fork-tender lamb shank simmered for 12 hours with ratan jot and Kashmiri chilies, served with fragrant golden saffron rice.",
                "ingredients": "12-Hour Braised Lamb Shank, Kashmiri Chili & Fennel Reduction, Clarified Ghee, Golden Saffron Pulao, Ginger Juliennes",
                "is_veg": False,
                "is_signature": True,
                "prep_time_mins": 10,
                "calories": 740,
                "spice_level": 3,
                "model_type": "curry",
                "rating": 4.99,
                "reviews_count": 390,
                "featured": False,
            },
            {
                "name": "Farzi Parle-G Cheesecake",
                "slug": "farzi-parle-g-cheesecake",
                "category": c_desserts,
                "price": 399.00,
                "tagline": "Nostalgic Biscuit Crust with Liquid Rabri Foam",
                "description": "Philadelphia cream cheese layered over spiced Parle-G biscuit crumble, topped with saffron cardamom foam and pistachio snow.",
                "ingredients": "Whipped Philadelphia Cream Cheese, Spiced Parle-G Biscuit Base, Cardamom Rabri Foam, Roasted Pistachio Snow, Gold Dust",
                "is_veg": True,
                "is_signature": True,
                "prep_time_mins": 5,
                "calories": 440,
                "spice_level": 0,
                "model_type": "dessert",
                "rating": 4.99,
                "reviews_count": 780,
                "featured": True,
            },
            {
                "name": "Liquid Nitrogen Gold Ghewar",
                "slug": "liquid-nitrogen-gold-ghewar",
                "category": c_desserts,
                "price": 459.00,
                "tagline": "Honeycomb Crisp with Flash Frozen Malai & 24K Gold Leaf",
                "description": "Traditional Rajasthani honeycomb ghewar flash-dipped in liquid nitrogen at -196C, topped with chilled malai mousse and pure gold foil.",
                "ingredients": "Rajasthani Crisp Honeycomb Tart, Flash-Frozen Saffron Malai, Sub-Zero Condensed Milk Snow, 24-Karat Edible Gold Leaf",
                "is_veg": True,
                "is_signature": True,
                "prep_time_mins": 6,
                "calories": 490,
                "spice_level": 0,
                "model_type": "dessert",
                "rating": 4.98,
                "reviews_count": 510,
                "featured": False,
            },
            {
                "name": "Bailey's Dark Chocolate Lollipops",
                "slug": "baileys-dark-chocolate-lollipops",
                "category": c_desserts,
                "price": 369.00,
                "tagline": "Chilled Belgium Ganache Popsicles with Popping Candy",
                "description": "Frozen chocolate spheres with Irish cream truffle core, glazed in 72% dark chocolate and rolled in crackling carbonated pop candy.",
                "ingredients": "72% Single-Origin Belgian Chocolate, Irish Cream Emulsion, Carbonated Popping Candy Crystals, Candied Hazelnut Dust",
                "is_veg": True,
                "is_signature": False,
                "prep_time_mins": 4,
                "calories": 320,
                "spice_level": 0,
                "model_type": "dessert",
                "rating": 4.92,
                "reviews_count": 320,
                "featured": False,
            },
            {
                "name": "Express Turbo Box (Vegetarian)",
                "slug": "express-turbo-box-veg",
                "category": c_combos,
                "price": 799.00,
                "tagline": "Arancini Pops + Charcoal Bao + Farzi Mist Potion",
                "description": "The ultimate flash delivery combo! 4 Dal Chawal Arancini Pops, 2 Charcoal Truffle Baos, and our signature Farzi Mist Cocktail.",
                "ingredients": "Dal Chawal Arancini, Charcoal Truffle Bao, Farzi Mist Mocktail, House Dips & Papad Crisp",
                "is_veg": True,
                "is_signature": True,
                "prep_time_mins": 6,
                "calories": 880,
                "spice_level": 1,
                "model_type": "burger",
                "rating": 4.98,
                "reviews_count": 610,
                "featured": True,
            },
            {
                "name": "Express Turbo Box (Gourmet Non-Veg)",
                "slug": "express-turbo-box-non-veg",
                "category": c_combos,
                "price": 999.00,
                "tagline": "Truffle Slider + Dynamite Prawns + Bourbon Illusion",
                "description": "Chef signature flash feast: Double Truffle Galouti Sliders, Tempura Dynamite Prawns, and Smoked Bourbon Illusion in thermal seal box.",
                "ingredients": "Truffle Galouti Slider, Tempura Fried Prawns, Smoked Bourbon Illusion, Sriracha Mayo, Potato Crisp Ribbons",
                "is_veg": False,
                "is_signature": True,
                "prep_time_mins": 7,
                "calories": 1120,
                "spice_level": 2,
                "model_type": "burger",
                "rating": 4.99,
                "reviews_count": 740,
                "featured": True,
            },
        ]

        for item_data in items:
            slug = item_data.pop("slug")
            MenuItem.objects.update_or_create(slug=slug, defaults=item_data)

        partners = [
            {"name": "Farhan 'Nitro' Qureshi", "phone": "+91 98110 54321", "vehicle_type": "Farzi Turbo Hyperspeed EV Bike", "vehicle_number": "DL-01-FZ-7701", "rating": 4.98, "avatar": "⚡", "active": True},
            {"name": "Zoya 'Flash' Mirza", "phone": "+91 98711 67890", "vehicle_type": "Farzi Mach-E Express Scooter", "vehicle_number": "DL-04-FZ-9904", "rating": 4.96, "avatar": "🚀", "active": True},
            {"name": "Kabir 'Thunder' Sen", "phone": "+91 99530 11223", "vehicle_type": "Farzi Jet-Pod Rapid EV", "vehicle_number": "DL-09-FZ-4412", "rating": 4.95, "avatar": "🏍️", "active": True},
        ]

        for p_data in partners:
            name = p_data.pop("name")
            DeliveryPartner.objects.update_or_create(name=name, defaults=p_data)

        self.stdout.write(self.style.SUCCESS(f"Successfully seeded {len(items)} Farzi items and delivery partners!"))
