# Generated by Django 6.0 on 2026-09-13 15:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(help_text='Emoji or icon identifier, e.g. 🍸, 🍔, 🔥, 🍨', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(default='Farzi Turbo Hyperspeed EV', max_length=100)),
                ('vehicle_number', models.CharField(default='FZ-TURBO-09', max_length=50)),
                ('rating', models.DecimalField(decimal_places=2, default=4.95, max_digits=3)),
                ('avatar', models.CharField(default='⚡', max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tagline', models.CharField(blank=True, help_text='e.g. Molecular Fog & Smoked Citrus', max_length=200)),
                ('description', models.TextField()),
                ('ingredients', models.TextField(help_text='Comma-separated ingredients for the 3D explosion view')),
                ('is_veg', models.BooleanField(default=False)),
                ('is_signature', models.BooleanField(default=False)),
                ('prep_time_mins', models.PositiveIntegerField(default=8)),
                ('calories', models.PositiveIntegerField(default=350)),
                ('spice_level', models.IntegerField(choices=[(0, 'Mild & Zero Heat'), (1, 'Gentle Warmth'), (2, 'Farzi Zesty Punch'), (3, 'Volcanic Fiery Heat')], default=1)),
                ('model_type', models.CharField(choices=[('cocktail', 'Farzi Smoked Cocktail Goblet'), ('burger', 'Gourmet Truffle Fusion Slider'), ('dessert', 'Liquid Nitrogen Sphere Dessert'), ('arancini', 'Dal Chawal Arancini Pops'), ('bao', 'Steamed Charcoal Truffle Bao'), ('curry', 'Smoking Claypot Butter Chicken')], default='burger', max_length=50)),
                ('rating', models.DecimalField(decimal_places=2, default=4.9, max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=84)),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('available', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cafe.category')),
            ],
            options={
                'ordering': ['-featured', '-is_signature', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_address', models.TextField()),
                ('delivery_pincode', models.CharField(default='110001', max_length=10)),
                ('delivery_notes', models.TextField(blank=True)),
                ('delivery_type', models.CharField(choices=[('turbo_15', 'Farzi Turbo 15-Min Guaranteed Express'), ('standard', 'Standard Gourmet Delivery')], default='turbo_15', max_length=30)),
                ('distance_km', models.FloatField(default=1.4)),
                ('status', models.CharField(choices=[('received', 'Order Received & Kitchen Alerted'), ('preparing', 'Molecular Gastronomy Prep & Cooking'), ('packed', 'Flash Nitrogen Thermal Sealed'), ('dispatched', 'Farzi Turbo Rider High-Speed Transit'), ('delivered', 'Arrived at Your Doorstep')], default='received', max_length=30)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(default='Farzi Turbo FastPay', max_length=50)),
                ('estimated_delivery_mins', models.PositiveIntegerField(default=14)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='cafe.deliverypartner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('customization', models.CharField(blank=True, max_length=200)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cafe.order')),
            ],
        ),
    ]
